version: "3.8"

services:
  api:
    build:
      context: .
      target: production
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    command: npm run start

  caching:
    image: redis

volumes:
  pgdata-dev:
